import{a as h,S as E,i as y}from"./assets/vendor-ee72e1a4.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const g="https://pixabay.com/api/";h.defaults.baseURL=g;const S="43918725-f2c9edad28ee6306c974c89a7",u=15,p=async(r="cat",e=1)=>{try{const s=new URLSearchParams({key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:u,page:e}),{data:l}=await h.get(`${g}?${s}`);return l}catch(s){console.log(s)}},P=document.querySelector("ul.gallery");document.querySelector(".btn-more");const q=new E(".gallery a",{captionPosition:"bottom",captionDelay:250,captionsData:"alt"}),f=async r=>{const e=await r.map(({webformatURL:l,largeImageURL:t,tags:o,likes:c,views:L,comments:b,downloads:w})=>`
     <li class="gallery-item">
      <a class="gallery-link" href="${t}">
        <img
          class="gallery-image"
          src="${l}"
          alt="${o}"
        />
        <div class="text-list">
          <p class="text-likes">Likes:${c}</p> 
          <p class="text-views">Views: ${L}</p>
          <p class="text-coments">Comments: ${b}</p>
         <p class="text-downloads">Downloads: ${w}</p>
        </div>
      </a>
    </li>
    `).join("");P.insertAdjacentHTML("beforeend",e),q.refresh();const s=document.querySelector(".loader");s.style.visibility="hidden",s.style.pointerEvents="none"},$=document.querySelector(".form"),a=document.querySelector(".loader"),v=document.querySelector("ul.gallery"),i=document.querySelector(".btn-more");let d,n=1,m=0;i.classList.add("d-none");$.addEventListener("submit",x);function x(r){r.preventDefault(),d=r.target.elements[0].value.trim(),r.target.reset(),a.style.visibility="visible",a.style.pointerEvents="all",d.length===0&&(a.style.visibility="hidden",a.style.pointerEvents="none",i.classList.add("d-none")),d&&(i.classList.add("d-none"),p(d).then(e=>{try{if(e.total===0)throw a.style.visibility="hidden",a.style.pointerEvents="none",new Error(y.show({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",color:"red",close:!0}));f(e.hits),u<e.total?(m=Math.ceil(e.total/u),m>1&&i.classList.remove("d-none")):y.show({position:"topRight",message:"We're sorry, but you've reached the end of search results",color:"red",close:!0})}catch(s){console.log(s)}v.innerHTML="",n=1}))}const R=()=>{const s=v.querySelector("li.gallery-item").getBoundingClientRect().height*5*n+100;window.scrollBy({top:s,left:0,behavior:"smooth"})},O=async r=>{try{n+=1,i.classList.remove("d-none");const e=await p(d,n);if(e.total===0)throw a.style.visibility="hidden",a.style.pointerEvents="none",i.classList.add("d-none"),new Error(y.show({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",color:"red",close:!0}));await f(e.hits),R(),u<e.total-u*n?m>1&&i.classList.remove("d-none"):i.classList.add("d-none"),n>=m&&y.show({position:"topRight",message:"We're sorry, but you've reached the end of search results",color:"red",close:!0})}catch(e){console.log(e)}};i.addEventListener("click",O);
//# sourceMappingURL=commonHelpers.js.map
