import{a as h,S,i as y}from"./assets/vendor-ee72e1a4.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const g="https://pixabay.com/api/";h.defaults.baseURL=g;const P="43918725-f2c9edad28ee6306c974c89a7",m=15,p=async(r="cat",e=1)=>{try{const s=new URLSearchParams({key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:m,page:e}),{data:n}=await h.get(`${g}?${s}`);return n}catch(s){console.log(s)}},q=document.querySelector("ul.gallery");document.querySelector(".btn-more");const $=new S(".gallery a",{captionPosition:"bottom",captionDelay:250,captionsData:"alt"}),f=async r=>{const e=await r.map(({webformatURL:n,largeImageURL:t,tags:o,likes:l,views:b,comments:E,downloads:w})=>`
     <li class="gallery-item">
      <a class="gallery-link" href="${t}">
        <img
          class="gallery-image"
          src="${n}"
          alt="${o}"
        />
        <div class="text-list">
          <p class="text-likes">Likes:${l}</p> 
          <p class="text-views">Views: ${b}</p>
          <p class="text-coments">Comments: ${E}</p>
         <p class="text-downloads">Downloads: ${w}</p>
        </div>
      </a>
    </li>
    `).join("");q.insertAdjacentHTML("beforeend",e),$.refresh();const s=document.querySelector(".loader");s.style.visibility="hidden",s.style.pointerEvents="none"},x=document.querySelector(".form"),a=document.querySelector(".loader"),v=document.querySelector("ul.gallery"),i=document.querySelector(".btn-more");let c,d=1,u=0;i.classList.add("d-none");x.addEventListener("submit",R);function R(r){r.preventDefault(),c=r.target.elements[0].value.trim(),r.target.reset(),a.style.visibility="visible",a.style.pointerEvents="all",c===0&&(a.style.visibility="hidden",a.style.pointerEvents="none",i.classList.add("d-none")),c&&p(c).then(e=>{try{if(e.total===0)throw a.style.visibility="hidden",a.style.pointerEvents="none",new Error(y.show({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",color:"red",close:!0}));f(e.hits),m<e.total&&(u=Math.ceil(e.total/m),u>1&&i.classList.remove("d-none"))}catch{}v.innerHTML="",d=1})}const O=()=>{const s=v.querySelector("li.gallery-item").getBoundingClientRect().height*5*d+100;console.log(s),window.scrollBy({top:s,left:0,behavior:"smooth"})},L=async r=>{try{d+=1,i.classList.remove("d-none");const e=await p(c,d);if(e.total===0)throw a.style.visibility="hidden",a.style.pointerEvents="none",i.classList.add("d-none"),new Error(y.show({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",color:"red",close:!0}));await f(e.hits),i.classList.add("d-none"),d>u?(i.classList.add("d-none"),i.removeEventListener("click",L),y.show({position:"topRight",message:"We're sorry, but you've reached the end of search results",color:"red",close:!0})):i.classList.remove("d-none"),O()}catch(e){console.log(e)}};i.addEventListener("click",L);
//# sourceMappingURL=commonHelpers.js.map
